package org.college.enums;

public enum State {
	DELAWARE, PENNSYLVANIA, NEW_JERSEY, GEORGIA, CONNECTICUT, MASSACHUSETTS, MARYLAND, SOUTH_CAROLLINA, NEW_HAMPSHIRE, VIRGINIA, NEW_YORK, NORTH_CAROLINA, RHODE_ISLAND, VERMONT, KENTUCKY, TENNESSEE, OHIO, LOUISIANA, INDIANA, MISSISSIPPI, ILLINOIS, ALABAMA, MAINE, MISSOURI, ARKANSAS, MICHIGAN, FLORIDA, TEXAS, IOWA, WISCONSIN, CALIFORNIA, MINNESOTA, OREGON, KANSAS, WEST_VIRGINIA, NEVADA, NEBRASKA, COLORADO, NORTH_DAKOTA, MONTANA, WASHINGTON, IDAHO, WYOMING, UTAH, OKLAHOMA, NEW_MEXICO, ARIZONA, ALASKA, HAWAII

}
